const closedA=['cat','ant','yak','ax','ram','jam','yam','dam','fan','man','pan','can','dad','pad','bag','rag','cap','map','nap','tap','bat','rat','hat','mat'];
const closedE=['web','egg','vet','ten','jet','net','wet','pet','hen','pen','red','bed'];
const closedI=['hip','ink','zip','in','lip','tip','sip','rip','bib','rib','kid','lid','pin','fin','bin','win','fig','wig','big','dig','pit','hit','six','mix'];
const closedO=['fox','log','ox','rod','pot','hot','cot','dot','top','mop','hop','pop'];
const closedU=['sun','up','jug','hug','bug','rug','mug','bud','mud','pup','cup','nut','hut','cut','cub','tub','gum','hum','bun','run','fun'];
const magicA=['tape','cape','cane','mane','game','cake','name','lake','gate','wave','skate','cave'];
const magicI=['kite','pine','ripe','fine','lime','bike','time','hike','five','nine','dive','line'];
const magicOU=['home','bone','cone','rope','cube','mute','cute','mule','tube','june','tune','rule'];
const openE=['she','we','me','he','be'];
const closedPool=[...closedA,...closedE,...closedI,...closedO,...closedU];
const openPool=openE;
const vowelRounds=[['cap','cape','a'],['tap','tape','a'],['can','cane','a'],['man','mane','a'],['dad','game','a'],['pin','pine','i'],['rip','ripe','i'],['fin','fine','i'],['hip','hike','i'],['lid','line','i'],['fox','home','o'],['rod','rope','o'],['hop','bone','o'],['cot','cone','o'],['cub','cube','u'],['cut','cute','u'],['tub','tube','u'],['gum','mute','u'],['pet','pete','e'],['bed','be','e']].map(([base,magic,vowel],i)=>({base,magic,vowel,hint:i<5?'Find the vowel in the short-a and magic-e words.':i<10?'Find the vowel that changes to a long sound.':'Compare both words and choose their vowel.'}));
const runWords=[['cat','Closed'],['she','Open'],['web','Closed'],['we','Open'],['hip','Closed'],['me','Open'],['fox','Closed'],['he','Open'],['sun','Closed'],['be','Open'],['ant','Closed'],['pet','Closed'],['ink','Closed'],['hop','Closed'],['cup','Closed'],['dad','Closed'],['red','Closed'],['fin','Closed'],['top','Closed'],['run','Closed']];
const runRounds=runWords.map(([word,type])=>({word,type,note:type==='Open'?`“${word}” ends in a vowel, so it is open.`:`“${word}” ends in a consonant, so it is closed.`}));
const starRounds=Array.from({length:20},(_,i)=>{const target=i%2?'Open':'Closed',right=target==='Open'?openPool:closedPool,wrong=target==='Open'?closedPool:openPool;const words=[];for(let j=0;j<3;j++){words.push([right[(i*3+j)%right.length],target]);words.push([wrong[(i*5+j)%wrong.length],target==='Open'?'Closed':'Open'])}return{target,words}});
const potionSource=['cat','ant','dad','cap','web','egg','jet','hen','hip','ink','pin','fin','fox','log','pot','hop','sun','cup','she','we'];
const potionRounds=potionSource.map(word=>{const vowel=[...word].find(char=>'aeiou'.includes(char));return{pattern:word.replace(vowel,'_'),word,vowel,type:openE.includes(word)?'Open':'Closed'}});
const dragonOrders=[[0,1,2],[1,2,0],[2,0,1],[0,2,1],[2,1,0],[1,0,2]];
const dragonRounds=Array.from({length:20},(_,i)=>{const eggs=[[openE[i%openE.length],'Open'],[closedPool[(i*2)%closedPool.length],'Closed'],[closedPool[(i*2+1)%closedPool.length],'Closed']];return dragonOrders[i%dragonOrders.length].map(position=>eggs[position])});
const starshipPairs={a:[['cap','cape'],['tap','tape'],['can','cane'],['man','mane']],i:[['kit','kite'],['pin','pine'],['rip','ripe'],['fin','fine']]};
const starshipSets=Object.fromEntries(Object.entries(starshipPairs).map(([vowel,pairs])=>[vowel,Array.from({length:20},(_,i)=>({base:pairs[i%pairs.length][0],magic:pairs[i%pairs.length][1],vowel,variant:i}))]));
const rounds={vowels:vowelRounds,run:runRounds,stars:starRounds,potion:potionRounds,dragon:dragonRounds,starship:[]};
const lastRoundOrders={};
const meta={vowels:['Magic Vowel Match','Choose the vowel that changes from short to long.'],run:['Castle Reading Run','Is the highlighted syllable open or closed?'],stars:['Syllable Stars','Collect only the stars with the requested syllable type!'],potion:['Potion Syllable Lab','Complete the word, then identify its syllable type.'],dragon:['Dragon Egg Rescue','Choose an egg and send it to the correct nest!'],starship:['Magic-E Starship','Choose a vowel mission, then launch final e!']};
const how={
 vowels:{title:'Magic Vowel Match',copy:'<ul><li>Read the first <b>closed-syllable</b> word.</li><li>Compare it with the magic-e word.</li><li>Choose the vowel whose sound changes from short to long.</li><li>Later rounds use longer consonant blends.</li></ul>'},
 run:{title:'Castle Reading Run',copy:'<ul><li>Read the word on the castle path.</li><li>An <b>open syllable</b> ends in a vowel; the vowel usually says its name.</li><li>A <b>closed syllable</b> ends in a consonant; the vowel is usually short.</li><li>Choose the correct type to continue the run.</li></ul>'},
 stars:{title:'Syllable Stars',copy:'<ul><li>Read the target at the top: <b>OPEN</b> or <b>CLOSED</b>.</li><li>Collect exactly three matching word stars.</li><li>A wrong star stays in the sky, so you can try again.</li><li>The syllables become less familiar as you progress.</li></ul>'},
 potion:{title:'Potion Syllable Lab',copy:'<ul><li>Choose the missing vowel to complete the word.</li><li>Then decide whether the shown syllable is <b>open</b> or <b>closed</b>.</li><li>Open syllables end in a vowel; closed syllables end in a consonant.</li><li>Complete both steps to brew the potion.</li></ul>'},
 dragon:{title:'Dragon Egg Rescue',copy:'<ul><li>Select one glowing egg and read its syllable.</li><li>Send it to the <b>OPEN</b> or <b>CLOSED</b> nest.</li><li>A correct egg hatches and earns stars.</li><li>Sort all three eggs to complete each rescue.</li></ul>'},
 starship:{title:'Magic-E Starship',copy:'<ul><li>Choose the <b>a</b> or <b>i</b> reading mission.</li><li>Read the closed-syllable word on the flying ship.</li><li>Press <b>ADD e</b> and watch the word transform.</li><li>Listen to both words, then press <b>NEXT</b>. Launch all 20 words to fill the star fuel.</li></ul>'}
};
const modal=document.querySelector('#game-modal'),board=document.querySelector('#game-board'),feedback=document.querySelector('#feedback'),onboarding=document.querySelector('#onboarding'),rules=document.querySelector('#rules');
let active='',index=0,roundScore=0,total=0,locked=false,selectedAvatar='',currentProfile=null,potionPhase='vowel',potionLevel=0,potionHue=285,gameCombo=0,gamePower=0,starshipVowel='',starshipFuel=0;
document.querySelector('#score').textContent=total;

// Student profile and first visit
onboarding.classList.add('open');
document.querySelectorAll('.avatar-grid button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.avatar-grid button').forEach(b=>b.classList.remove('selected'));button.classList.add('selected');selectedAvatar=button.dataset.avatar;validateProfile()});
document.querySelector('#student-name').addEventListener('input',validateProfile);
document.querySelector('#enter-academy').onclick=()=>{const name=document.querySelector('#student-name').value.trim();currentProfile={name,avatar:selectedAvatar};total=0;roundScore=0;document.querySelector('#score').textContent='0';document.querySelector('#round-score').textContent='0';applyProfile(currentProfile);onboarding.classList.remove('open');startMusic();playSound(true)};
document.querySelector('#profile-button').onclick=()=>{const p=currentProfile;document.querySelector('#student-name').value=p?.name||'';selectedAvatar=normalizeAvatar(p?.avatar)||'';document.querySelectorAll('.avatar-grid button').forEach(b=>b.classList.toggle('selected',b.dataset.avatar===selectedAvatar));validateProfile();onboarding.classList.add('open')};
function validateProfile(){document.querySelector('#enter-academy').disabled=!(document.querySelector('#student-name').value.trim()&&selectedAvatar)}
function normalizeAvatar(value){return({"avatar-boy.png":'boy',"avatar-girl.png":'girl',"avatar-reader.png":'reader',"avatar-owl.png":'owl'})[value]||value}
function applyProfile(p){const avatar=normalizeAvatar(p.avatar)||'boy';document.querySelector('#profile-name').textContent=p.name;document.querySelector('#profile-avatar').className=`profile-picture avatar-${avatar}`}

// Game and instruction overlays
document.querySelectorAll('.game-card').forEach(c=>{const fn=()=>openGame(c.dataset.game);c.addEventListener('click',fn);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')fn()})});
document.querySelector('.close').onclick=closeGame;modal.onclick=e=>{if(e.target===modal)closeGame()};document.onkeydown=e=>{if(e.key==='Escape'){rules.classList.remove('open');closeGame()}};document.querySelector('#restart').onclick=start;
document.querySelector('#how-button').onclick=showRules;document.querySelector('.rules-close').onclick=hideRules;document.querySelector('.got-it').onclick=hideRules;rules.onclick=e=>{if(e.target===rules)hideRules()};
function showRules(){document.querySelector('#rules-title').textContent=how[active].title;document.querySelector('#rules-copy').innerHTML=how[active].copy;rules.classList.add('open')}
function hideRules(){rules.classList.remove('open')}
function openGame(id){active=id;const panel=document.querySelector('.panel');panel.classList.remove('game-vowels','game-run','game-stars','game-potion','game-dragon','game-starship');panel.classList.add(`game-${id}`);document.querySelector('#game-title').textContent=meta[id][0];document.querySelector('#game-instruction').textContent=meta[id][1];modal.classList.add('open');modal.setAttribute('aria-hidden','false');start()}
function closeGame(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
function shuffleGameRounds(id){const shuffled=[...rounds[id]];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}let signature=JSON.stringify(shuffled);if(signature===lastRoundOrders[id]&&shuffled.length>1){shuffled.push(shuffled.shift());signature=JSON.stringify(shuffled)}rounds[id].splice(0,rounds[id].length,...shuffled);lastRoundOrders[id]=signature}
function start(){if(active==='starship'){starshipVowel='';starshipFuel=0;rounds.starship.splice(0)}else shuffleGameRounds(active);index=0;roundScore=0;locked=false;potionPhase='vowel';potionLevel=0;potionHue=285;gameCombo=0;gamePower=0;document.querySelector('#round-score').textContent=0;feedback.textContent='';feedback.className='feedback';render()}
function updateProgress(){document.querySelector('#question-number').textContent=Math.min(index+1,20);document.querySelector('#progress-fill').style.width=((index+1)/20*100)+'%'}
function reward(){roundScore+=10;total+=10;document.querySelector('#round-score').textContent=roundScore;document.querySelector('#score').textContent=total;const t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),850)}
function playSound(correct){const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;const ctx=playSound.ctx||(playSound.ctx=new AudioCtx());const notes=correct?[523.25,659.25,783.99]:[220,164.81];notes.forEach((freq,i)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=correct?'sine':'sawtooth';osc.frequency.value=freq;gain.gain.setValueAtTime(.001,ctx.currentTime+i*.1);gain.gain.exponentialRampToValueAtTime(correct?.12:.08,ctx.currentTime+i*.1+.015);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+i*.1+.18);osc.connect(gain).connect(ctx.destination);osc.start(ctx.currentTime+i*.1);osc.stop(ctx.currentTime+i*.1+.2)})}

// Procedural mysterious background music: no external audio file or autoplay permission needed.
const music={ctx:null,gain:null,bus:null,echo:null,timer:null,started:false,muted:localStorage.getItem('wizard-music-muted')==='true',volume:Number(localStorage.getItem('wizard-music-volume')||28)/100};
const musicToggle=document.querySelector('#music-toggle'),musicVolume=document.querySelector('#music-volume');musicVolume.value=Math.round(music.volume*100);
function syncMusicUI(){musicToggle.classList.toggle('muted',music.muted);musicToggle.textContent=music.muted?'♩̸':'♫';musicToggle.setAttribute('aria-label',music.muted?'Turn music on':'Mute music')}
function startMusic(){if(music.started)return;const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;music.ctx=new AudioCtx();music.gain=music.ctx.createGain();music.bus=music.ctx.createBiquadFilter();music.bus.type='lowpass';music.bus.frequency.value=5200;music.echo=music.ctx.createDelay(1);const feedback=music.ctx.createGain(),echoLevel=music.ctx.createGain();music.echo.delayTime.value=.42;feedback.gain.value=.24;echoLevel.gain.value=.22;music.echo.connect(feedback).connect(music.echo);music.echo.connect(echoLevel).connect(music.gain);music.bus.connect(music.gain);music.gain.gain.value=music.muted?0:music.volume*.22;music.gain.connect(music.ctx.destination);music.started=true;scheduleMusic();music.timer=setInterval(scheduleMusic,12800)}
function musicNote(freq,when,duration,type='sine',level=.1,attack=.12,detune=0,echo=.12){const osc=music.ctx.createOscillator(),gain=music.ctx.createGain(),send=music.ctx.createGain();osc.type=type;osc.frequency.value=freq;osc.detune.value=detune;send.gain.value=echo;gain.gain.setValueAtTime(.001,when);gain.gain.exponentialRampToValueAtTime(level,when+attack);gain.gain.exponentialRampToValueAtTime(.001,when+duration);osc.connect(gain);gain.connect(music.bus);gain.connect(send).connect(music.echo);osc.start(when);osc.stop(when+duration+.08)}
function scheduleMusic(){if(!music.ctx)return;const t=music.ctx.currentTime+.08,chords=[[146.83,174.61,220],[116.54,146.83,174.61],[130.81,174.61,220],[130.81,164.81,196]],harp=[[293.66,349.23,440,523.25],[233.08,293.66,349.23,440],[261.63,349.23,440,523.25],[261.63,329.63,392,493.88]];chords.forEach((chord,c)=>{const at=t+c*3.2;musicNote(chord[0]/2,at,3.18,'sine',.12,.7,-7,.08);chord.forEach((n,j)=>{musicNote(n,at,3.12,j===1?'triangle':'sine',.045,.85,j*6-6,.08);musicNote(n*2,at+.04,2.9,'sine',.012,.95,-j*4,.16)});harp[c].forEach((n,j)=>{const hit=at+.18+j*.62;musicNote(n,hit,1.45,'triangle',.07,.025,0,.34);musicNote(n*2,hit+.03,.8,'sine',.025,.018,4,.42)});musicNote(harp[c][2]*2,at+2.72,1.1,'sine',.035,.02,0,.48)})}
function setMusicLevel(){if(!music.gain)return;music.gain.gain.cancelScheduledValues(music.ctx.currentTime);music.gain.gain.setTargetAtTime(music.muted?0:music.volume*.22,music.ctx.currentTime,.08)}
musicToggle.onclick=e=>{e.stopPropagation();startMusic();music.muted=!music.muted;localStorage.setItem('wizard-music-muted',music.muted);setMusicLevel();syncMusicUI()};
musicVolume.oninput=()=>{startMusic();music.volume=Number(musicVolume.value)/100;if(music.volume>0)music.muted=false;localStorage.setItem('wizard-music-volume',musicVolume.value);localStorage.setItem('wizard-music-muted',music.muted);setMusicLevel();syncMusicUI()};
document.addEventListener('pointerdown',()=>startMusic(),{once:true});syncMusicUI();
function answer(ok,note,next){if(locked)return;locked=true;playSound(ok);feedback.textContent=ok?'Correct! ✦ '+note:'Not quite. '+note;feedback.className='feedback '+(ok?'good':'bad');if(ok)reward();setTimeout(()=>{feedback.textContent='';feedback.className='feedback';locked=false;index++;next()},1100)}
function render(){if(active==='vowels')renderVowels();if(active==='run')renderRun();if(active==='stars')renderStars();if(active==='potion')renderPotion();if(active==='dragon')renderDragon();if(active==='starship')renderStarship()}
function complete(){playSound(true);board.innerHTML='<div class="choice-board"><div class="prompt-card">🏆</div><h2>Brilliant reading magic!</h2><p>You completed all 20 challenges.</p></div>';document.querySelector('#game-instruction').textContent='Challenge complete — your reading magic is strong!';document.querySelector('#progress-fill').style.width='100%';document.querySelector('#question-number').textContent='20'}
function questHud(label){return `<div class="quest-hud"><span>✦ ${label}</span><div class="quest-meter"><i style="width:${gamePower}%"></i></div><small>Streak <b>${gameCombo}</b> 🔥</small></div>`}
function updateQuestMagic(ok){gameCombo=ok?gameCombo+1:0;gamePower=Math.max(0,Math.min(100,gamePower+(ok?5:-3)));const hud=board.querySelector('.quest-hud');if(hud){hud.querySelector('.quest-meter i').style.width=gamePower+'%';hud.querySelector('small b').textContent=gameCombo;hud.classList.toggle('charged',ok)}}
function renderVowels(){const data=rounds.vowels;if(index>=20)return complete();updateProgress();const q=data[index];board.innerHTML=`<div class="choice-board magical-board vowel-magic">${questHud('SPELL POWER')}<div class="lesson-scroll"><div class="vowel-pair"><span>${q.base}</span><i>➜</i><span>${q.magic}</span></div></div><p class="magic-hint">${q.hint}</p><div class="answers charm-answers">${['a','e','i','o','u'].map((v,i)=>`<button class="answer vowel-charm charm-${i}" data-v="${v}"><b>${v}</b></button>`).join('')}</div></div>`;board.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{const ok=b.dataset.v===q.vowel;b.classList.add(ok?'correct':'wrong');updateQuestMagic(ok);answer(ok,ok?`${q.vowel.toUpperCase()} changes to its long sound.`:`Listen to the vowel in “${q.base}”.`,renderVowels)})}
function renderRun(){const q=rounds.run[index];if(index>=20)return complete();updateProgress();const shown=q.marked?`${q.marked} · ${q.word.slice(q.marked.length)}`:q.word;board.innerHTML=`<div class="choice-board magical-board run-magic">${questHud('CASTLE PATH')}<div class="lesson-scroll run-scroll"><div class="prompt-card">${shown}</div></div><p class="magic-hint">How does the ${q.marked?'first ':''}syllable end?</p><div class="answers rune-answers"><button class="answer rune-answer" data-v="Open"><i>☀</i><span>Open syllable</span></button><button class="answer rune-answer" data-v="Closed"><i>◆</i><span>Closed syllable</span></button></div></div>`;board.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{const ok=b.dataset.v===q.type;b.classList.add(ok?'correct':'wrong');updateQuestMagic(ok);answer(ok,q.note,renderRun)})}
function renderStars(){if(index>=20)return complete();updateProgress();const q=rounds.stars[index];document.querySelector('#game-instruction').textContent=`Collect the ${q.target.toUpperCase()} syllable stars!`;board.innerHTML=`<div class="star-board">${q.words.map(([w,t])=>`<button class="word-star" data-type="${t}" aria-label="${w}, ${t} syllable"><img src="assets/word-star-plain-3d.png" alt=""><span class="star-word">${w}</span></button>`).join('')}</div>`;let found=0;board.querySelectorAll('.word-star').forEach(b=>b.onclick=()=>{const word=b.querySelector('.star-word').textContent;if(b.dataset.type===q.target){b.classList.add('used');found++;playSound(true);reward();feedback.textContent='Great choice!';feedback.className='feedback good';if(found===3){locked=true;setTimeout(()=>{index++;locked=false;feedback.textContent='';renderStars()},900)}}else{playSound(false);b.animate([{transform:'rotate(-5deg)'},{transform:'rotate(5deg)'},{transform:'rotate(0)'}],{duration:260});feedback.textContent=`“${word}” is a ${b.dataset.type.toLowerCase()} syllable.`;feedback.className='feedback bad'}})}
