const closedA=['cat','ant','yak','ax','ram','jam','yam','dam','fan','man','pan','can','dad','pad','bag','rag','cap','map','nap','tap','bat','rat','hat','mat'];
const closedE=['web','egg','vet','ten','jet','net','wet','pet','hen','pen','red','bed'];
const closedI=['hip','ink','zip','in','lip','tip','sip','rip','bib','rib','kid','lid','pin','fin','bin','win','fig','wig','big','dig','pit','hit','six','mix'];
const closedO=['fox','log','ox','rod','pot','hot','cot','dot','top','mop','hop','pop'];
const closedU=['sun','up','jug','hug','bug','rug','mug','bud','mud','pup','cup','nut','hut','cut','cub','tub','gum','hum','bun','run','fun'];
const magicA=['tape','cape','cane','mane','game','cake','name','lake','gate','wave','skate','cave'];
const magicI=['kite','pine','ripe','fine','lime','bike','time','hike','five','nine','dive','line'];
const magicOU=['home','bone','cone','rope','cube','mute','cute','mule','tube','june','tune','rule'];
const openE=['she','we','me','he','be'];
const dragonOrders=[[0,1,2],[1,2,0],[2,0,1],[0,2,1],[2,1,0],[1,0,2]];
const vowelsList=['a','i','e','o','u'];
const closedByVowel={a:closedA,i:closedI,e:closedE,o:closedO,u:closedU};
const openByVowel={a:magicA,i:magicI,e:openE,o:['home','bone','cone','rope'],u:['cube','mute','cute','mule','tube','june','tune','rule']};
const starshipPairs={a:[['cap','cape'],['tap','tape'],['can','cane'],['man','mane']],i:[['kit','kite'],['pin','pine'],['rip','ripe'],['fin','fine']],e:[['pet','pete'],['her','here'],['them','theme'],['met','mete']],o:[['hop','hope'],['not','note'],['rod','rode'],['cop','cope']],u:[['cub','cube'],['tub','tube'],['cut','cute'],['us','use']]};
const rounds={vowels:[],run:[],stars:[],potion:[],dragon:[],starship:[]};
const lastRoundOrders={};
function missionVowels(mission){return Array.from({length:20},(_,i)=>mission==='mix'?vowelsList[i%vowelsList.length]:mission)}
function buildMissionRounds(id,mission){const sequence=missionVowels(mission);if(id==='vowels'||id==='starship')return sequence.map((vowel,i)=>{const pair=starshipPairs[vowel][i%starshipPairs[vowel].length];return{base:pair[0],magic:pair[1],vowel,hint:`Read both words. Which vowel changes from short to long?`}});if(id==='run')return sequence.map((vowel,i)=>{const type=i%2?'Open':'Closed',pool=type==='Open'?openByVowel[vowel]:closedByVowel[vowel],word=pool[i%pool.length];return{word,type,note:type==='Open'?`“${word}” has a long ${vowel} sound.`:`“${word}” has a short ${vowel} sound in a closed syllable.`}});if(id==='stars')return sequence.map((vowel,i)=>{const target=i%2?'Open':'Closed',right=target==='Open'?openByVowel[vowel]:closedByVowel[vowel],wrong=target==='Open'?closedByVowel[vowel]:openByVowel[vowel],words=[];for(let j=0;j<3;j++){words.push([right[(i+j)%right.length],target]);words.push([wrong[(i+j*2)%wrong.length],target==='Open'?'Closed':'Open'])}return{target,words,vowel}});if(id==='potion')return sequence.map((vowel,i)=>{const type=i%2?'Open':'Closed',pool=type==='Open'?openByVowel[vowel]:closedByVowel[vowel],word=pool[i%pool.length];return{pattern:word.replace(vowel,'_'),word,vowel,type}});if(id==='dragon')return sequence.map((vowel,i)=>{const eggs=[[openByVowel[vowel][i%openByVowel[vowel].length],'Open'],[closedByVowel[vowel][(i*2)%closedByVowel[vowel].length],'Closed'],[closedByVowel[vowel][(i*2+1)%closedByVowel[vowel].length],'Closed']];return dragonOrders[i%dragonOrders.length].map(position=>eggs[position])});return[]}
const meta={vowels:['Magic Vowel Match','Choose the vowel that changes from short to long.'],run:['Castle Reading Run','Is the highlighted syllable open or closed?'],stars:['Syllable Stars','Collect only the stars with the requested syllable type!'],potion:['Potion Syllable Lab','Complete the word, then identify its syllable type.'],dragon:['Dragon Egg Rescue','Choose an egg and send it to the correct nest!'],starship:['Magic-E Starship','Choose a vowel mission, then launch final e!']};
const how={
 vowels:{title:'Magic Vowel Match',copy:'<ul><li>Read the first <b>closed-syllable</b> word.</li><li>Compare it with the magic-e word.</li><li>Choose the vowel whose sound changes from short to long.</li><li>Later rounds use longer consonant blends.</li></ul>'},
 run:{title:'Castle Reading Run',copy:'<ul><li>Read the word on the castle path.</li><li>An <b>open syllable</b> ends in a vowel; the vowel usually says its name.</li><li>A <b>closed syllable</b> ends in a consonant; the vowel is usually short.</li><li>Choose the correct type to continue the run.</li></ul>'},
 stars:{title:'Syllable Stars',copy:'<ul><li>Read the target at the top: <b>OPEN</b> or <b>CLOSED</b>.</li><li>Collect exactly three matching word stars.</li><li>A wrong star stays in the sky, so you can try again.</li><li>The syllables become less familiar as you progress.</li></ul>'},
 potion:{title:'Potion Syllable Lab',copy:'<ul><li>Choose the missing vowel to complete the word.</li><li>Then decide whether the shown syllable is <b>open</b> or <b>closed</b>.</li><li>Open syllables end in a vowel; closed syllables end in a consonant.</li><li>Complete both steps to brew the potion.</li></ul>'},
 dragon:{title:'Dragon Egg Rescue',copy:'<ul><li>Select one glowing egg and read its syllable.</li><li>Send it to the <b>OPEN</b> or <b>CLOSED</b> nest.</li><li>A correct egg hatches and earns stars.</li><li>Sort all three eggs to complete each rescue.</li></ul>'},
 starship:{title:'Magic-E Starship',copy:'<ul><li>Choose one vowel or the <b>MIX</b> mission.</li><li>Read the closed-syllable word on the flying ship.</li><li>Press <b>ADD e</b> and watch the word transform.</li><li>Press <b>NEXT</b> and launch all 20 words to fill the star fuel.</li></ul>'}
};
const modal=document.querySelector('#game-modal'),board=document.querySelector('#game-board'),feedback=document.querySelector('#feedback'),onboarding=document.querySelector('#onboarding'),rules=document.querySelector('#rules');
let active='',index=0,roundScore=0,total=0,locked=false,selectedAvatar='',currentProfile=null,potionPhase='vowel',potionLevel=0,potionHue=285,gameCombo=0,gamePower=0,selectedVowel='',starshipFuel=0;
document.querySelector('#score').textContent=total;

// Student profile and first visit
onboarding.classList.add('open');
document.querySelectorAll('.avatar-grid button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.avatar-grid button').forEach(b=>b.classList.remove('selected'));button.classList.add('selected');selectedAvatar=button.dataset.avatar;validateProfile()});
document.querySelector('#student-name').addEventListener('input',validateProfile);
document.querySelector('#enter-academy').onclick=()=>{const name=document.querySelector('#student-name').value.trim();currentProfile={name,avatar:selectedAvatar};total=0;roundScore=0;document.querySelector('#score').textContent='0';document.querySelector('#round-score').textContent='0';applyProfile(currentProfile);onboarding.classList.remove('open');playSound(true)};
document.querySelector('#profile-button').onclick=()=>{const p=currentProfile;document.querySelector('#student-name').value=p?.name||'';selectedAvatar=normalizeAvatar(p?.avatar)||'';document.querySelectorAll('.avatar-grid button').forEach(b=>b.classList.toggle('selected',b.dataset.avatar===selectedAvatar));validateProfile();onboarding.classList.add('open')};
function validateProfile(){document.querySelector('#enter-academy').disabled=!(document.querySelector('#student-name').value.trim()&&selectedAvatar)}
function normalizeAvatar(value){return({"avatar-boy.png":'boy',"avatar-girl.png":'girl',"avatar-reader.png":'reader',"avatar-owl.png":'owl'})[value]||value}
function applyProfile(p){const avatar=normalizeAvatar(p.avatar)||'boy';document.querySelector('#profile-name').textContent=p.name;document.querySelector('#profile-avatar').className=`profile-picture avatar-${avatar}`}

// Game and instruction overlays
document.querySelectorAll('.game-card').forEach(c=>{const fn=()=>openGame(c.dataset.game);c.addEventListener('click',fn);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')fn()})});
document.querySelector('.close').onclick=closeGame;modal.onclick=e=>{if(e.target===modal)closeGame()};document.onkeydown=e=>{if(e.key==='Escape'){rules.classList.remove('open');closeGame()}};document.querySelector('#restart').onclick=start;
document.querySelector('#how-button').onclick=showRules;document.querySelector('.rules-close').onclick=hideRules;document.querySelector('.got-it').onclick=hideRules;rules.onclick=e=>{if(e.target===rules)hideRules()};
function showRules(){document.querySelector('#rules-title').textContent=how[active].title;document.querySelector('#rules-copy').innerHTML=how[active].copy;rules.classList.add('open')}
function hideRules(){rules.classList.remove('open')}
function openGame(id){active=id;const panel=document.querySelector('.panel');panel.classList.remove('game-vowels','game-run','game-stars','game-potion','game-dragon','game-starship');panel.classList.add(`game-${id}`);document.querySelector('#game-title').textContent=meta[id][0];document.querySelector('#game-instruction').textContent=meta[id][1];modal.classList.add('open');modal.setAttribute('aria-hidden','false');start()}
function closeGame(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
function shuffleGameRounds(id){const shuffled=[...rounds[id]];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}let signature=JSON.stringify(shuffled);if(signature===lastRoundOrders[id]&&shuffled.length>1){shuffled.push(shuffled.shift());signature=JSON.stringify(shuffled)}rounds[id].splice(0,rounds[id].length,...shuffled);lastRoundOrders[id]=signature}
function start(){selectedVowel='';starshipFuel=0;rounds[active].splice(0);index=0;roundScore=0;locked=false;potionPhase='vowel';potionLevel=0;potionHue=285;gameCombo=0;gamePower=0;document.querySelector('#round-score').textContent=0;feedback.textContent='';feedback.className='feedback';render()}
function updateProgress(){document.querySelector('#question-number').textContent=Math.min(index+1,20);document.querySelector('#progress-fill').style.width=((index+1)/20*100)+'%'}
function reward(){roundScore+=10;total+=10;document.querySelector('#round-score').textContent=roundScore;document.querySelector('#score').textContent=total;const t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),850)}
function playSound(correct){const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;const ctx=playSound.ctx||(playSound.ctx=new AudioCtx());const notes=correct?[523.25,659.25,783.99]:[220,164.81];notes.forEach((freq,i)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=correct?'sine':'sawtooth';osc.frequency.value=freq;gain.gain.setValueAtTime(.001,ctx.currentTime+i*.1);gain.gain.exponentialRampToValueAtTime(correct?.12:.08,ctx.currentTime+i*.1+.015);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+i*.1+.18);osc.connect(gain).connect(ctx.destination);osc.start(ctx.currentTime+i*.1);osc.stop(ctx.currentTime+i*.1+.2)})}

function answer(ok,note,next){if(locked)return;locked=true;playSound(ok);feedback.textContent=ok?'Correct! ✦ '+note:'Not quite. '+note;feedback.className='feedback '+(ok?'good':'bad');if(ok)reward();setTimeout(()=>{feedback.textContent='';feedback.className='feedback';locked=false;index++;next()},1100)}
function render(){if(!selectedVowel)return renderVowelMission();if(active==='vowels')renderVowels();if(active==='run')renderRun();if(active==='stars')renderStars();if(active==='potion')renderPotion();if(active==='dragon')renderDragon();if(active==='starship')renderStarship()}
function renderVowelMission(){document.querySelector('#game-instruction').textContent='Choose one vowel or practise all vowels in MIX mode.';document.querySelector('#progress-fill').style.width='0%';document.querySelector('#question-number').textContent='1';const options=[...vowelsList,'mix'];board.innerHTML=`<div class="vowel-mission"><span>SELECT YOUR READING MISSION</span><h3>Which vowel would you like to practise?</h3><div>${options.map(v=>`<button data-mission="${v}" class="mission-${v}"><b>${v==='mix'?'MIX':v}</b><small>${v==='mix'?'a · i · e · o · u':'20 reading challenges'}</small></button>`).join('')}</div></div>`;board.querySelectorAll('[data-mission]').forEach(button=>button.onclick=()=>{selectedVowel=button.dataset.mission;rounds[active].splice(0,rounds[active].length,...buildMissionRounds(active,selectedVowel));shuffleGameRounds(active);document.querySelector('#game-instruction').textContent=selectedVowel==='mix'?'Mixed vowel mission: a, i, e, o, u.':`Vowel mission: ${selectedVowel.toUpperCase()}.`;render()})}
function complete(){playSound(true);board.innerHTML='<div class="choice-board"><div class="prompt-card">🏆</div><h2>Brilliant reading magic!</h2><p>You completed all 20 challenges.</p></div>';document.querySelector('#game-instruction').textContent='Challenge complete — your reading magic is strong!';document.querySelector('#progress-fill').style.width='100%';document.querySelector('#question-number').textContent='20'}
function questHud(label){return `<div class="quest-hud"><span>✦ ${label}</span><div class="quest-meter"><i style="width:${gamePower}%"></i></div><small>Streak <b>${gameCombo}</b> 🔥</small></div>`}
function updateQuestMagic(ok){gameCombo=ok?gameCombo+1:0;gamePower=Math.max(0,Math.min(100,gamePower+(ok?5:-3)));const hud=board.querySelector('.quest-hud');if(hud){hud.querySelector('.quest-meter i').style.width=gamePower+'%';hud.querySelector('small b').textContent=gameCombo;hud.classList.toggle('charged',ok)}}
function renderVowels(){const data=rounds.vowels;if(index>=20)return complete();updateProgress();const q=data[index];board.innerHTML=`<div class="choice-board magical-board vowel-magic">${questHud('SPELL POWER')}<div class="lesson-scroll"><div class="vowel-pair"><span>${q.base}</span><i>➜</i><span>${q.magic}</span></div></div><p class="magic-hint">${q.hint}</p><div class="answers charm-answers">${['a','e','i','o','u'].map((v,i)=>`<button class="answer vowel-charm charm-${i}" data-v="${v}"><b>${v}</b></button>`).join('')}</div></div>`;board.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{const ok=b.dataset.v===q.vowel;b.classList.add(ok?'correct':'wrong');updateQuestMagic(ok);answer(ok,ok?`${q.vowel.toUpperCase()} changes to its long sound.`:`Listen to the vowel in “${q.base}”.`,renderVowels)})}
function renderRun(){const q=rounds.run[index];if(index>=20)return complete();updateProgress();const shown=q.marked?`${q.marked} · ${q.word.slice(q.marked.length)}`:q.word;board.innerHTML=`<div class="choice-board magical-board run-magic">${questHud('CASTLE PATH')}<div class="lesson-scroll run-scroll"><div class="prompt-card">${shown}</div></div><p class="magic-hint">How does the ${q.marked?'first ':''}syllable end?</p><div class="answers rune-answers"><button class="answer rune-answer" data-v="Open"><i>☀</i><span>Open syllable</span></button><button class="answer rune-answer" data-v="Closed"><i>◆</i><span>Closed syllable</span></button></div></div>`;board.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{const ok=b.dataset.v===q.type;b.classList.add(ok?'correct':'wrong');updateQuestMagic(ok);answer(ok,q.note,renderRun)})}
function renderStars(){if(index>=20)return complete();updateProgress();const q=rounds.stars[index];document.querySelector('#game-instruction').textContent=`Collect the ${q.target.toUpperCase()} syllable stars!`;board.innerHTML=`<div class="star-board">${q.words.map(([w,t])=>`<button class="word-star" data-type="${t}" aria-label="${w}, ${t} syllable"><img src="assets/word-star-plain-3d.png" alt=""><span class="star-word">${w}</span></button>`).join('')}</div>`;let found=0;board.querySelectorAll('.word-star').forEach(b=>b.onclick=()=>{const word=b.querySelector('.star-word').textContent;if(b.dataset.type===q.target){b.classList.add('used');found++;playSound(true);reward();feedback.textContent='Great choice!';feedback.className='feedback good';if(found===3){locked=true;setTimeout(()=>{index++;locked=false;feedback.textContent='';renderStars()},900)}}else{playSound(false);b.animate([{transform:'rotate(-5deg)'},{transform:'rotate(5deg)'},{transform:'rotate(0)'}],{duration:260});feedback.textContent=`“${word}” is a ${b.dataset.type.toLowerCase()} syllable.`;feedback.className='feedback bad'}})}
