const vowelRounds=[
 ['cap','cape','a'],['kit','kite','i'],['hop','hope','o'],['cub','cube','u'],['pet','pete','e'],
 ['mad','made','a'],['rid','ride','i'],['not','note','o'],['cut','cute','u'],['them','theme','e'],
 ['plan','plane','a'],['strip','stripe','i'],['glob','globe','o'],['tub','tube','u'],['met','mete','e'],
 ['scrap','scrape','a'],['spin','spine','i'],['slop','slope','o'],['us','use','u'],['breath','breathe','e']
].map(([base,magic,vowel],i)=>({base,magic,vowel,hint:i<5?'Choose the vowel that changes from short to long.':i<10?'Listen carefully: which vowel says its name?':'Use the word pattern and find the long vowel.'}));
const runRounds=[
 ['cat','Closed','The syllable ends in a consonant. A is short.'],['he','Open','It ends in a vowel. E says its name.'],['kit','Closed','It ends in a consonant. I is short.'],['go','Open','It ends in a vowel. O says its name.'],['sun','Closed','It ends in a consonant. U is short.'],
 ['me','Open','It ends in a vowel. E says its name.'],['robot','Open','The first syllable “ro” ends in a vowel.','ro'],['music','Open','The first syllable “mu” ends in a vowel.','mu'],['rabbit','Closed','The first syllable “rab” ends in a consonant.','rab'],['lemon','Closed','The first syllable “lem” ends in a consonant.','lem'],
 ['tulip','Open','The first syllable “tu” is open.','tu'],['hotel','Open','The first syllable “ho” is open.','ho'],['picnic','Closed','The first syllable “pic” is closed.','pic'],['basic','Open','The first syllable “ba” is open.','ba'],['finish','Closed','The first syllable “fin” is closed.','fin'],
 ['moment','Open','The first syllable “mo” is open.','mo'],['rapid','Closed','The first syllable “rap” is closed.','rap'],['unit','Open','The first syllable “u” is open.','u'],['planet','Closed','The first syllable “plan” is closed.','plan'],['student','Open','The first syllable “stu” is open.','stu']
].map(([word,type,note,marked])=>({word,type,note,marked}));
const openPool=['a','be','he','me','she','we','go','no','so','hi','mu','ro','tu','ba','flu','pro','tri','stu','ze','lo'];
const closedPool=['cat','bed','sit','top','sun','nap','red','fin','hop','cup','rab','lem','pic','plan','run','dog','met','kit','glob','cut'];
const starRounds=Array.from({length:20},(_,i)=>{const target=i%2?'Open':'Closed',right=target==='Open'?openPool:closedPool,wrong=target==='Open'?closedPool:openPool;const words=[];for(let j=0;j<3;j++){words.push([right[(i*2+j)%20],target]);words.push([wrong[(i*3+j)%20],target==='Open'?'Closed':'Open'])}return{target,words:words.sort((a,b)=>a[0].localeCompare(b[0]))}});
const rounds={vowels:vowelRounds,run:runRounds,stars:starRounds};
const meta={vowels:['Magic Vowel Match','Choose the vowel that changes from short to long.'],run:['Castle Reading Run','Is the highlighted syllable open or closed?'],stars:['Syllable Stars','Collect only the stars with the requested syllable type!']};
const how={
 vowels:{title:'Magic Vowel Match',copy:'<ul><li>Read the first <b>closed-syllable</b> word.</li><li>Compare it with the magic-e word.</li><li>Choose the vowel whose sound changes from short to long.</li><li>Later rounds use longer consonant blends.</li></ul>'},
 run:{title:'Castle Reading Run',copy:'<ul><li>An <b>open syllable</b> ends in a vowel; the vowel usually says its name.</li><li>A <b>closed syllable</b> ends in a consonant; the vowel is usually short.</li><li>For longer words, classify only the separated first syllable.</li></ul>'},
 stars:{title:'Syllable Stars',copy:'<ul><li>Read the target at the top: <b>OPEN</b> or <b>CLOSED</b>.</li><li>Collect exactly three matching word stars.</li><li>A wrong star stays in the sky, so you can try again.</li><li>The syllables become less familiar as you progress.</li></ul>'}
};
const modal=document.querySelector('#game-modal'),board=document.querySelector('#game-board'),feedback=document.querySelector('#feedback'),onboarding=document.querySelector('#onboarding'),rules=document.querySelector('#rules');
let active='',index=0,roundScore=0,total=Number(localStorage.getItem('wizard-score')||1250),locked=false,selectedAvatar='';
document.querySelector('#score').textContent=total;

// Student profile and first visit
const savedProfile=JSON.parse(localStorage.getItem('wizard-profile')||'null');
if(savedProfile)applyProfile(savedProfile);else onboarding.classList.add('open');
document.querySelectorAll('.avatar-grid button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.avatar-grid button').forEach(b=>b.classList.remove('selected'));button.classList.add('selected');selectedAvatar=button.dataset.avatar;validateProfile()});
document.querySelector('#student-name').addEventListener('input',validateProfile);
document.querySelector('#enter-academy').onclick=()=>{const name=document.querySelector('#student-name').value.trim();const profile={name,avatar:selectedAvatar};localStorage.setItem('wizard-profile',JSON.stringify(profile));applyProfile(profile);onboarding.classList.remove('open');startMusic();playSound(true)};
document.querySelector('#profile-button').onclick=()=>{const p=JSON.parse(localStorage.getItem('wizard-profile')||'null');document.querySelector('#student-name').value=p?.name||'';selectedAvatar=normalizeAvatar(p?.avatar)||'';document.querySelectorAll('.avatar-grid button').forEach(b=>b.classList.toggle('selected',b.dataset.avatar===selectedAvatar));validateProfile();onboarding.classList.add('open')};
function validateProfile(){document.querySelector('#enter-academy').disabled=!(document.querySelector('#student-name').value.trim()&&selectedAvatar)}
function normalizeAvatar(value){return({"avatar-boy.png":'boy',"avatar-girl.png":'girl',"avatar-reader.png":'reader',"avatar-owl.png":'owl'})[value]||value}
function applyProfile(p){const avatar=normalizeAvatar(p.avatar)||'boy';document.querySelector('#profile-name').textContent=p.name;document.querySelector('#profile-avatar').className=`profile-picture avatar-${avatar}`}

// Game and instruction overlays
document.querySelectorAll('.game-card').forEach(c=>{const fn=()=>openGame(c.dataset.game);c.addEventListener('click',fn);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')fn()})});
document.querySelector('.close').onclick=closeGame;modal.onclick=e=>{if(e.target===modal)closeGame()};document.onkeydown=e=>{if(e.key==='Escape'){rules.classList.remove('open');closeGame()}};document.querySelector('#restart').onclick=start;
document.querySelector('#how-button').onclick=showRules;document.querySelector('.rules-close').onclick=hideRules;document.querySelector('.got-it').onclick=hideRules;rules.onclick=e=>{if(e.target===rules)hideRules()};
function showRules(){document.querySelector('#rules-title').textContent=how[active].title;document.querySelector('#rules-copy').innerHTML=how[active].copy;rules.classList.add('open')}
function hideRules(){rules.classList.remove('open')}
function openGame(id){active=id;const panel=document.querySelector('.panel');panel.classList.remove('game-vowels','game-run','game-stars');panel.classList.add(`game-${id}`);document.querySelector('#game-title').textContent=meta[id][0];document.querySelector('#game-instruction').textContent=meta[id][1];modal.classList.add('open');modal.setAttribute('aria-hidden','false');start()}
function closeGame(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
function start(){index=0;roundScore=0;locked=false;document.querySelector('#round-score').textContent=0;feedback.textContent='';feedback.className='feedback';render()}
function updateProgress(){document.querySelector('#question-number').textContent=Math.min(index+1,20);document.querySelector('#progress-fill').style.width=((index+1)/20*100)+'%'}
function reward(){roundScore+=10;total+=10;document.querySelector('#round-score').textContent=roundScore;document.querySelector('#score').textContent=total;localStorage.setItem('wizard-score',total);const t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),850)}
function playSound(correct){const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;const ctx=playSound.ctx||(playSound.ctx=new AudioCtx());const notes=correct?[523.25,659.25,783.99]:[220,164.81];notes.forEach((freq,i)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=correct?'sine':'sawtooth';osc.frequency.value=freq;gain.gain.setValueAtTime(.001,ctx.currentTime+i*.1);gain.gain.exponentialRampToValueAtTime(correct?.12:.08,ctx.currentTime+i*.1+.015);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+i*.1+.18);osc.connect(gain).connect(ctx.destination);osc.start(ctx.currentTime+i*.1);osc.stop(ctx.currentTime+i*.1+.2)})}

// Procedural mysterious background music: no external audio file or autoplay permission needed.
const music={ctx:null,gain:null,bus:null,echo:null,timer:null,started:false,muted:localStorage.getItem('wizard-music-muted')==='true',volume:Number(localStorage.getItem('wizard-music-volume')||28)/100};
const musicToggle=document.querySelector('#music-toggle'),musicVolume=document.querySelector('#music-volume');musicVolume.value=Math.round(music.volume*100);
function syncMusicUI(){musicToggle.classList.toggle('muted',music.muted);musicToggle.textContent=music.muted?'♩̸':'♫';musicToggle.setAttribute('aria-label',music.muted?'Turn music on':'Mute music')}
function startMusic(){if(music.started)return;const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;music.ctx=new AudioCtx();music.gain=music.ctx.createGain();music.bus=music.ctx.createBiquadFilter();music.bus.type='lowpass';music.bus.frequency.value=5200;music.echo=music.ctx.createDelay(1);const feedback=music.ctx.createGain(),echoLevel=music.ctx.createGain();music.echo.delayTime.value=.42;feedback.gain.value=.24;echoLevel.gain.value=.22;music.echo.connect(feedback).connect(music.echo);music.echo.connect(echoLevel).connect(music.gain);music.bus.connect(music.gain);music.gain.gain.value=music.muted?0:music.volume*.22;music.gain.connect(music.ctx.destination);music.started=true;scheduleMusic();music.timer=setInterval(scheduleMusic,12800)}
function musicNote(freq,when,duration,type='sine',level=.1,attack=.12,detune=0,echo=.12){const osc=music.ctx.createOscillator(),gain=music.ctx.createGain(),send=music.ctx.createGain();osc.type=type;osc.frequency.value=freq;osc.detune.value=detune;send.gain.value=echo;gain.gain.setValueAtTime(.001,when);gain.gain.exponentialRampToValueAtTime(level,when+attack);gain.gain.exponentialRampToValueAtTime(.001,when+duration);osc.connect(gain);gain.connect(music.bus);gain.connect(send).connect(music.echo);osc.start(when);osc.stop(when+duration+.08)}
function scheduleMusic(){if(!music.ctx)return;const t=music.ctx.currentTime+.08,chords=[[146.83,174.61,220],[116.54,146.83,174.61],[130.81,174.61,220],[130.81,164.81,196]],harp=[[293.66,349.23,440,523.25],[233.08,293.66,349.23,440],[261.63,349.23,440,523.25],[261.63,329.63,392,493.88]];chords.forEach((chord,c)=>{const at=t+c*3.2;musicNote(chord[0]/2,at,3.18,'sine',.12,.7,-7,.08);chord.forEach((n,j)=>{musicNote(n,at,3.12,j===1?'triangle':'sine',.045,.85,j*6-6,.08);musicNote(n*2,at+.04,2.9,'sine',.012,.95,-j*4,.16)});harp[c].forEach((n,j)=>{const hit=at+.18+j*.62;musicNote(n,hit,1.45,'triangle',.07,.025,0,.34);musicNote(n*2,hit+.03,.8,'sine',.025,.018,4,.42)});musicNote(harp[c][2]*2,at+2.72,1.1,'sine',.035,.02,0,.48)})}
function setMusicLevel(){if(!music.gain)return;music.gain.gain.cancelScheduledValues(music.ctx.currentTime);music.gain.gain.setTargetAtTime(music.muted?0:music.volume*.22,music.ctx.currentTime,.08)}
musicToggle.onclick=e=>{e.stopPropagation();startMusic();music.muted=!music.muted;localStorage.setItem('wizard-music-muted',music.muted);setMusicLevel();syncMusicUI()};
musicVolume.oninput=()=>{startMusic();music.volume=Number(musicVolume.value)/100;if(music.volume>0)music.muted=false;localStorage.setItem('wizard-music-volume',musicVolume.value);localStorage.setItem('wizard-music-muted',music.muted);setMusicLevel();syncMusicUI()};
document.addEventListener('pointerdown',()=>startMusic(),{once:true});syncMusicUI();
function answer(ok,note,next){if(locked)return;locked=true;playSound(ok);feedback.textContent=ok?'Correct! ✦ '+note:'Not quite. '+note;feedback.className='feedback '+(ok?'good':'bad');if(ok)reward();setTimeout(()=>{feedback.textContent='';feedback.className='feedback';locked=false;index++;next()},1100)}
function render(){if(active==='vowels')renderVowels();if(active==='run')renderRun();if(active==='stars')renderStars()}
function complete(){playSound(true);board.innerHTML='<div class="choice-board"><div class="prompt-card">🏆</div><h2>Brilliant reading magic!</h2><p>You completed all 20 challenges.</p></div>';document.querySelector('#game-instruction').textContent='Challenge complete — your reading magic is strong!';document.querySelector('#progress-fill').style.width='100%';document.querySelector('#question-number').textContent='20'}
function renderVowels(){const data=rounds.vowels;if(index>=20)return complete();updateProgress();const q=data[index];board.innerHTML=`<div class="choice-board"><div class="vowel-pair"><span>${q.base}</span><i>➜</i><span>${q.magic}</span></div><p>${q.hint}</p><div class="answers">${['a','e','i','o','u'].map(v=>`<button class="answer" data-v="${v}">${v}</button>`).join('')}</div></div>`;board.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{const ok=b.dataset.v===q.vowel;b.classList.add(ok?'correct':'wrong');answer(ok,ok?`${q.vowel.toUpperCase()} changes to its long sound.`:`Listen to the vowel in “${q.base}”.`,renderVowels)})}
function renderRun(){const q=rounds.run[index];if(index>=20)return complete();updateProgress();const shown=q.marked?`${q.marked} · ${q.word.slice(q.marked.length)}`:q.word;board.innerHTML=`<div class="choice-board"><div class="prompt-card">${shown}</div><p>How does the ${q.marked?'first ':''}syllable end?</p><div class="answers"><button class="answer" data-v="Open">Open syllable</button><button class="answer" data-v="Closed">Closed syllable</button></div></div>`;board.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{const ok=b.dataset.v===q.type;b.classList.add(ok?'correct':'wrong');answer(ok,q.note,renderRun)})}
function renderStars(){if(index>=20)return complete();updateProgress();const q=rounds.stars[index];document.querySelector('#game-instruction').textContent=`Collect the ${q.target.toUpperCase()} syllable stars!`;board.innerHTML=`<div class="star-board">${q.words.map(([w,t])=>`<button class="word-star" data-type="${t}">${w}</button>`).join('')}</div>`;let found=0;board.querySelectorAll('.word-star').forEach(b=>b.onclick=()=>{if(b.dataset.type===q.target){b.classList.add('used');found++;playSound(true);reward();feedback.textContent='Great choice!';feedback.className='feedback good';if(found===3){locked=true;setTimeout(()=>{index++;locked=false;feedback.textContent='';renderStars()},900)}}else{playSound(false);b.animate([{transform:'rotate(-5deg)'},{transform:'rotate(5deg)'},{transform:'rotate(0)'}],{duration:260});feedback.textContent=`“${b.textContent}” is a ${b.dataset.type.toLowerCase()} syllable.`;feedback.className='feedback bad'}})}
